// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LogoLinkedIn: typeof import('./src/components/LogoLinkedIn.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Quote: typeof import('./src/components/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeaSkyAnimation: typeof import('./src/components/SeaSkyAnimation.vue')['default']
    Section: typeof import('./src/components/Section.vue')['default']
    Square: typeof import('./src/components/Square.vue')['default']
    Squares: typeof import('./src/components/Squares.vue')['default']
    TextSection: typeof import('./src/components/TextSection.vue')['default']
  }
}
